version: '2'
services:
  i:
    build: microservices/i/.
    volumes:
      - ./microservices/i:/app
  s:
    build: microservices/s/.
    volumes:
      - ./microservices/s:/app
  w:
    build : microservices/w/.
    ports:
      - "8090:8090"
  b:
    build : microservices/b/.
    volumes:
      - ./microservices/b:/app
  web:
    build: webserver/.
    volumes:
      - ./webserver/app:/app
    ports:
      - "80:80"
  p:
    build: microservices/p/.
    volumes:
      - ./microservices/p:/app
  db_i:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
    # ports:
    #   - 3306:3306
    volumes:
      - ./db_i:/docker-entrypoint-initdb.d
  db_s:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    # ports:
    #   - 3306:3306
    volumes:
      - ./db_s:/docker-entrypoint-initdb.d
